### ISSUE TITLE
New feature requests

### ISSUE THREAD

**Issue by Agasthya7** [will-moss/erin#2]
It works great although a few minor issues which if rectified will improve the functionality.

- **Support for Nested Folders**. Now it only looks under the videos directory and all the files should be directly under this directory. If the program looks for the files which are present in the folders inside the videos directory, it helps in terms of organization for the backend.
- **Adjusting the aspect ratio**. It's currently under a stretch to match screensize. It would be better if it maintains the native aspect ratio.
- **Mute button**. It's not visible in the mobile screens

**Comment by will-moss** [comment]
Thank you for opening the issue and providing those details.

I will try to fix everything and publish a new release asap.

**Comment by will-moss** [comment]
Hey!

I've just published a big release with new fixes, bugs, and improvements.

You may be interested in the following : 
- Nested folders are now supported : Erin will recursively scan your whole videos folder for mp4, webm, and ogg video files.
- The videos' aspect ratio is now untouched : No more stretching or deformation, the videos are now kept as they are.
- The app's style was partly rewritten : The mute button should be displayed properly now, and the video isn't cut anymore on the bottom.

Does that work better for you?

Let me know, and thanks again for opening the issue.
