### ISSUE TITLE
Erin over internet - with nginx proxy manager

### ISSUE THREAD

**Issue by ChipXinhDep** [will-moss/erin#5]
Currently I running Erin in docker compose in portainer. It run perfectly in Lan but I can't make it run over internet. 
Normally with all my other apps, i only need to add external nginxnetwork at last row, then config like my picture below in GUI of Nginx Proxy Manager, add CNAME in cloudflare and everything runs perfectly but didnt with Erin.
I'm using Nginx Proxy Manager to controll all stuffs so i really not want to change to caddy server. Is there any way i can config Erin to run with NPM ?
Below are my docker composer and pictures of my config in NPM:

```dockerfile
services:
  erin:
    image: mosswill/erin:latest
    ports:
      - "100.101.115.121:447:447"
    volumes:
      - /home/mrz/docker/tiktok:/srv/videos:ro
    environment:
      PUBLIC_URL: "http://100.101.115.121:447"
      AUTH_ENABLED: "false"
networks:
  default:
    external:
      name: nginxnetwork
``` 
![image](https://github.com/user-attachments/assets/ca48dfaf-5a5a-480e-b3fc-626272213131)

**Comment by will-moss** [comment]
Hi !

Thanks for explaining everything.

I think you're just a few tweaks away from resolving your issue.

Please mind that I don't use NPM myself, but still, this is what I would change : 

- In your `docker-compose.yml` file : 

  - Change the variable `PUBLIC_URL` to `http://tiktok.mydomain.com`
    - This variable instructs Caddy what `Host` and `Port` it should be bound to.
    - Currently, you are bound to 100.101.115.121 on the port 447.
    - However, you wish to reach Erin using `tiktok.mydomain.com`.
    - So, you must first use that domain in place of the IP address.
      - Otherwise, you would need to access Erin using the IP address, not the domain.
   - Ultimately, unless you type `http://tiktok.mydomain.com:447`, you want to use the port 80 or 443.
     - This is why I would remove the port entirely from the variable `PUBLIC_URL`.
     - Caddy shall run on port 80, using HTTP, and responding to the requests to the host `tiktok.mydomain.com` 

  - Replace your port binding with an `expose` clause, for the port 80, rather than 447.
    - Given that NPM is bound to ports 80 and 443 on the host machine, it will receive all the requests.
    - Then, internally, NPM will forward those requests to Erin, on a "virtual" port, the port 80 on Erin's container.
    - As a result, you shouldn't need to have Erin occupy any port on the host machine at all, because all communication happen inside Docker and its virtual networks.

  - In your NPM configuration (the popup in your screenshot) : 
    - I'm not 100% sure, but I assume you should change the field `Forward port` to use 80 rather than 447.
    - In my understanding, this field instructs NPM what virtual port the forwarded-to container uses.
    - In our case, after the aforementioned edits, it should be 80.


 Does that work for you?

**Comment by ChipXinhDep** [comment]
Oh man Erin now works perfectly over internet ! Thanks !
